#!/usr/bin/env python3
# /// script
# dependencies = [
#   "click",
#   "abook_parser",
# ]
# ///

import os
import click

pth = os.environ["ABOOK_FILE"]

from abook_parser.parser import AbookFile, Fzf

fzf = Fzf()


@click.command()
@click.option("-c", "--clipboard", is_flag=True, help="Copy to clipboard")
def main(clipboard: bool) -> None:
    ab = AbookFile(path=pth)
    mem: dict[str, dict[str, str]] = {}
    feed = []
    for contact in ab.contacts:
        if "name" not in contact:
            continue
        key = contact["name"]
        if "nick" in contact:
            key += f" ({contact['nick']})"
        mem[key] = contact
        feed.append(key)

    chosen = fzf.prompt(feed, "--no-multi")
    if not chosen:
        return

    chosen = mem[chosen[0]]
    picked = fzf.prompt([f"{key}={val}" for key, val in chosen.items()], "--multi")
    if not picked:
        return

    print_items = [p.split("=", maxsplit=1)[1] for p in picked]
    text = "\n".join(print_items)
    click.echo(text)
    if clipboard:
        from pura.clipboard import clipcopy

        clipcopy(text)


if __name__ == "__main__":
    main()
