#!/usr/bin/env bash
SCRIPT="${1?:No script provided}"
shift || true
declare SCRIPT_PATH="$SCRIPT"
if [[ ! -f "$SCRIPT_PATH" ]]; then
	SCRIPT_PATH="$(which "$SCRIPT_PATH")"
fi
exec bash -x "$SCRIPT_PATH" "$@"
