#!/bin/sh
# pass a duration for fd as the first argument, otherwise defaults to 2 weeks
dir="$HOME/.local/share/PhoneCamera"
case "$ON_OS" in
android_termux*)
	dir="$HOME/storage/dcim"
	;;
esac
exec fd jpg "$dir" --changed-within "${1:-2weeks}" -x image-auto-rotate
