#!/usr/bin/env python3

import sys
import urlextract

extractor = urlextract.URLExtract()


def main() -> None:
    """
    Add < > around URLs, meant to suppress links in markdown/discord message text
    """
    for line in sys.stdin:
        urls = extractor.find_urls(line, get_indices=True)
        # this handles the case when there are multiple URLs per line
        if urls:
            with_supressed = ""
            last_end = 0
            for u, (start, end) in urls:
                with_supressed += line[last_end:start] + f"<{u}>"
                last_end = end  # move past the last replaced URL
            with_supressed += line[last_end:]  # rest of the line after last URL
            print(with_supressed, end="")
        else:
            print(line, end="")


if __name__ == "__main__":
    main()
