#!/usr/bin/env bash
# uses auto-subtitle (a local openai whisper subtitle generator wrapper) script
# installed in a pipx venv:
# https://purarue.xyz/d/auto-subtitle-install?redirect

file="$1"
if [[ ! -f "$file" ]]; then
	echo "Usage: $0 <file>"
	exit 1
fi

full_path="$(realpath "$file")"
srt_path="${full_path%.*}.srt"
if [[ ! -f "$srt_path" ]]; then
	echo "Generating subtitles for $full_path" >&2
	auto_subtitle --srt_only true "$full_path" --model medium.en || {
		echo "Failed to generate subtitles for $file" >&2
		rm -f "$srt_path"
	}
fi
