#!/usr/bin/env bash
# uses auto-subtitle (a local openai whisper subtitle generator wrapper) script
# installed in a pipx venv:
# to install, first install pipx (run 'python3 -m pip install pipx')
# then run auto-subtitle-install script:
#
# that requires pyenv to be setup:
# https://github.com/pyenv/pyenv
#
# https://purarue.xyz/d/auto-subtitle-install?redirect

if [[ ! -f "$1" ]]; then
	echo "Usage: $0 <FILE...>"
	exit 1
fi

process_file() {
	file="$1"
	full_path="$(realpath "$file")"
	srt_path="${full_path%.*}.srt"
	if [[ ! -f "$srt_path" ]]; then
		echo "Generating subtitles for $full_path" >&2
		auto_subtitle --srt_only true "$full_path" --model medium.en || {
			echo "Failed to generate subtitles for $file" >&2
			rm -f "$srt_path"
		}
	fi
}

for file in "$@"; do
	process_file "$file"
done
