#!/usr/bin/env python3
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "click>=8.3.1",
# ]
# ///

import click

HEARTS = [
    "❤️",
    "🧡",
    "💛",
    "💚",
    "💙",
    "💜",
    "🤍",
    "🤎",
    "💖",
]


@click.command()
@click.option("-a", "--all", "_all", is_flag=True, help="Print all hearts")
def main(_all: bool) -> None:
    chosen: str
    if _all:
        chosen = "".join(HEARTS)
    else:

        import random

        chosen = random.choice(HEARTS)
    click.echo(chosen)


if __name__ == "__main__":
    main()
