#!/usr/bin/env python3
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "jsonc-parser>=1.1.5",
# ]
# ///

import json
import fileinput
import contextlib
from typing import Any

from jsonc_parser.parser import JsoncParser


def main() -> None:
    lines: list[str] = list(fileinput.input())
    data: Any = JsoncParser.parse_str("\n".join(lines))
    print(json.dumps(data, indent=4))


if __name__ == "__main__":
    with contextlib.suppress(KeyboardInterrupt):
        main()
