#!/usr/bin/env bash
# generates a jumplist of directories, so I can cd to one
# https://purarue.xyz/d/cd.zsh?dark
#
# using
# and the commits modules to scan my local repos
# https://github.com/karlicoss/HPI/blob/master/my/coding/commits.py

set -e
set -o pipefail

{
	hpi query my.coding.commits.repos -s | jq -r
} | grep -v '^/tmp' | unique || exit $?
