#!/usr/bin/env python3

import click
import typing
from geopy.geocoders import Nominatim  # type: ignore


def get_lat_lon(query: typing.Sequence[str]) -> tuple[float, float]:
    geolocator = Nominatim(user_agent="purarue.xyz/get_lat_lon")
    try:
        location = geolocator.geocode(" ".join(query))
        if location:
            return location.latitude, location.longitude
        else:
            raise Exception("couldnt fetch fetch")
    except Exception as e:
        return f"An error occurred: {e}"


@click.command()
@click.argument("QUERY", nargs=-1)
def main(query) -> None:
    res = get_lat_lon(query)
    click.echo(res)


if __name__ == "__main__":
    main()
