#!/usr/bin/env python3
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "click>=8.3.1",
#     "geopy>=2.4.1",
# ]
# ///

import click
import typing
from geopy.geocoders import Nominatim  # type: ignore


def get_lat_lon(query: typing.Sequence[str]) -> tuple[float, float]:
    geolocator = Nominatim(user_agent="https://purarue.xyz/d/location-to-gps")
    location = geolocator.geocode(" ".join(query))
    if location:
        return location.latitude, location.longitude
    else:
        raise Exception("couldn't fetch location")


@click.command()
@click.argument("QUERY", nargs=-1)
def main(query) -> None:
    try:
        lat, lon = get_lat_lon(query)
    except Exception as e:
        click.Abort(str(e))
    click.echo(f"{lat},{lon}")


if __name__ == "__main__":
    main()
