#!/usr/bin/env python3


import sys
import shutil
from tempfile import NamedTemporaryFile
from pathlib import Path

import click

from my.mail.mbox import _iter_mailbox


@click.command()
@click.option(
    "--format",
    default="%s",
    help="Date output format",
)
@click.argument("FILE", type=click.Path(exists=True, dir_okay=False, path_type=Path))
def main(format: str, file: Path) -> None:
    with NamedTemporaryFile() as temp_file:
        shutil.copy(file, temp_file.name)
        msgs = list(_iter_mailbox(Path(temp_file.name)))
        exit_code = 0
        for msg in msgs:
            if msg.dt is not None:
                click.echo(msg.dt.strftime(format))
            else:
                exit_code = 1
                click.echo(f"NO DATE: {msg.subject}")

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
