#!/usr/bin/env python3
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "click>=8.3.1",
# ]
# ///

import click

mapping = {
    "A": "Alpha",
    "B": "Bravo",
    "C": "Charlie",
    "D": "Delta",
    "E": "Echo",
    "F": "Foxtrot",
    "G": "Golf",
    "H": "Hotel",
    "I": "India",
    "J": "Juliet",
    "K": "Kilo",
    "L": "Lima",
    "M": "Mike",
    "N": "November",
    "O": "Oscar",
    "P": "Papa",
    "Q": "Quebec",
    "R": "Romeo",
    "S": "Sierra",
    "T": "Tango",
    "U": "Uniform",
    "V": "Victor",
    "W": "Whiskey",
    "X": "X-ray",
    "Y": "Yankee",
    "Z": "Zulu",
}


@click.command()
@click.argument("TEXT", required=False)
def main(text: str | None) -> None:
    inp = text or click.prompt("Enter text")
    for char in inp:
        c = char.upper()
        if c in mapping:
            print(mapping[c])
        else:
            print(char)


if __name__ == "__main__":
    main()
