#!/usr/bin/env bash

set -e

input="${1:?provide input file as first argument}"
output="${2?:provide output file as second argument}"

if ! command -v weasyprint >/dev/null; then
	# shellcheck disable=SC2016
	echo 'Could not find weasyprint on your $PATH' >&2
	exit 1
fi

tmpfile="$(mktemp)"
trap 'rm "$tmpfile"' EXIT

cat <<EOF >"$tmpfile"
---
page-size: Letter
mainfont: sans-serif
---
EOF

cat "$input" >>"$tmpfile"
exec pandoc -f markdown+hard_line_breaks --pdf-engine=weasyprint -o "$output" <"$tmpfile"
# TODO: if output is an HTML file, wrap this in a HTML/head with utf-8 and some basic CSS?
# or maybe make another script?
