#!/usr/bin/env bash
# starts a timer which ends at a particular point in the future
# e.g. timer-till 'today at 10pm'
# I often use this with https://purarue.xyz/d/playping-loop?redirect,
# as a sort of alarm/reminder to do something, like:
# timer-till 'today at 4pm' && playping-loop

declare at now
now="$(epoch)"
at="$(dateq parse -Fepoch "today at $*")" || return $?
[[ -z "$at" ]] && exit 1

if [[ "$at" -le "$now" ]]; then
	echo "Time must be in the future, parsed $(dateq parse -Ftime "$at"), now is $(dateq parse -Ftime "$now")" >&2
	exit 1
fi

exec timer -f "$((at - now))s"
