#!/usr/bin/env bash
# change modification for a file, interactively
file="${1:-$(gum file)}" || exit $?
[[ -n "$1" ]] && shift
time="${*:-(gum input --prompt="Date> ")}" || exit $?
dt="$(dateq parse -F '%Y%m%d%H%M' "$time")" || exit $?
exec touch -amt "$dt" "$file"
