#!/usr/bin/env bash
# fetches all the upcoming wca competitions
current_date="$(date +%Y-%m-%d)"
pagination_size=''
page=1
while true; do
	data="$(curl -sL "https://www.worldcubeassociation.org/api/v0/competition_index?include_cancelled=false&sort=start_date%2Cend_date%2Cname&ongoing_and_future=$current_date&page=$page")"
	count=$(echo "$data" | jq 'length')
	jq '.[]' <<<"$data"
	if [[ -z "$pagination_size" ]]; then
		pagination_size="$count"
	else
		# if we hit something without the default pagination size, then were done
		if [[ "$count" != "$pagination_size" ]]; then
			break
		fi
	fi
	((page++))
done
