#!/usr/bin/env bash
# Gets the youtube ID for a user from a link
# Could be a link to their channel or a video
# Searches the <meta> tags for a channelId value

yt-dlp --print channel_url --playlist-items 1 "${1:?Pass the URL as the first argument}" | awk -F/ '{print $NF}'
