#!/usr/bin/env bash
# print the corresponding youtube RSS feed and name
# can pass a youtube link or channel URL as input
# this is the RSS format expected by newsraft
data="$(yt-dlp --print channel_url --print channel --playlist-items 1 "${1?Provide a youtube url}")"
channel_id="$(awk -F'/' 'NR == 1 {print $NF}' <<<"$data")"
name="$(tail -n1 <<<"$data")"
[[ -z "$channel_id" ]] && exit
printf 'https://www.youtube.com/feeds/videos.xml?channel_id=%s "%s"\n' "${channel_id}" "${name}"
