#!/usr/bin/env bash

items="$(reminder-sink run)"
count="$(awk 'NF > 0 { count++ } END { print count }' <<<"$items")"
text="$(colorize_number "$count")"
jq -rcn --arg text " $text" --arg items "$items" '{"text": $text, "tooltip": $items}'
