# move backups off my phone into my regular data directories
# any directory which exists in ~/data/phone/
# also exists in ~/data
#
# moving files from ~/data/phone to ~/data
# gets rid of the files on my phone
# since ~/data/phone syncs with syncthing
#
# e.g. move all files from
# ~/data/phone/gpslogger/file.gpx
# ... to
# ~/data/gpslogger/file.gpx
rules:
  - folders:
      - "~/data/phone"
      - "! ~/data/phone/ttally/" # ignore ttally, want to keep that on my phone
    filters:
      - lastmodified:
          days: 1 # move files once they havent been modified for 1 day
    subfolders: true # match all subfolders
    actions:
      - move:
          dest: "{basedir.parent}/{path.parent.stem}/{path.name}"
          overwrite: false
          counter_separator: "_"
