#!/usr/bin/env bash
# if there are comments to approve, warn me

CACHE_FILE="$HOME/.cache/guestbook-comments"
[[ -f $CACHE_FILE ]] || exit 2

EXIT=0
if FILE="$(is-integer "$(cat "$CACHE_FILE")")"; then
	[[ $FILE -gt 0 ]] && exit 2
fi

exit "$EXIT"
