#!/usr/bin/env bash
# if there are comments to approve, warn me

CACHE_FILE="$HOME/.cache/guestbook-comments"
[[ ! -f $CACHE_FILE ]] && exit 0

EXIT=0
if COMMENT_COUNT="$(is-integer "$(cat "$CACHE_FILE")")"; then
	((COMMENT_COUNT > 0)) && EXIT=2
fi

exit "$EXIT"
