#!/bin/sh
# https://www.discogs.com/search?q=sampha&type=all
# searches discogs for an album
SEARCH_STR=$(input-dialog "Search for an album > " | chomp | tr " " "+")
[ -z "$SEARCH_STR" ] && exit 1
exec openurl "https://www.discogs.com/search/?q=${SEARCH_STR}&type=all"
