#!/bin/sh
cd ~ || exit $?
# fuzzy match list-config names, open one to edit (Edit Config)
chosen="$(fzfcache list-config-no-hist | sed "s#^$HOME/##g" | fzfp +m -q "$*")" || return $?
[ -n "$chosen" ] && exec vim "$chosen"
