#!/bin/sh
# searches letterboxd for a movie
[ -z "$SEARCH_STR" ] && SEARCH_STR=$(input-dialog "Search for a movie > " | chomp | tr " " "+")
[ -z "$SEARCH_STR" ] && exit 1
exec openurl "https://letterboxd.com/search/films/${SEARCH_STR}"
