#!/usr/bin/env bash
TARGET="${XDG_CONFIG_HOME}/ranger/preview.rc"
case "${ON_OS:-$(on_machine)}" in
android*)
	# dont think there's any way to do this right now
	echo 'set preview_images false' >"${TARGET}"
	;;
linux_arch*)
	printf 'set preview_images %s\n' "${RANGER_GENERATE_IMAGE_PREVIEW:-true}" >"${TARGET}"
	if [[ "$TERM" == xterm-kitty ]]; then
		# use kitty to preview images
		echo 'set preview_images_method kitty' >>"${TARGET}"
	elif [[ "$TERM" == foot ]]; then
		echo 'set preview_images_method sixel' >>"${TARGET}"
	else
		# use ueberzug to preview images
		echo 'set preview_images_method ueberzug' >>"${TARGET}"
	fi
	;;
*)
	# fallback to w3m?
	echo -e 'set preview_images true\nset preview_images_method w3m' >"${TARGET}"
	;;
esac
