#!/usr/bin/env bash

if [[ -z "$oname" ]]; then
	printf "oname not set\n" >&2
	exit 1
fi

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

set -x

exec jinjanate ./hidden_template.rc >hidden_filter.rc
