#!/usr/bin/env bash
# stuff to run on my computer at home
# has a X display, so can be used for chromedriver (doesn't work on
# my wayland right now, idk)

set -x

ONCE=0
[[ "$1" == '-o' ]] && ONCE=1

run() {

	# make sure my pythonanywhere website doesn't expire:
	# https://github.com/purarue/pythonanywhere-3-months
	evry 2 months -pythonanywhere && python3 -m pythonanywhere_3_months -c "$(which chromedriver)"

	evry 1 week -sync-dbsentinel && {
		(cd "$REPOS/dbsentinel" && ./scripts/sync_from_remote)
	}

	# https://github.com/purarue/grouvee_export
	evry 2 months -grouvee-export && python3 -m grouvee_export export

	# https://github.com/purarue/albums
	# try to resolve releases to their collection URLs/refresh expired album data
	evry 1 week -discogs-update && {
		(cd "$REPOS/albums" && ./update -r)
	}
	evry 3 days -auto-mal-update && {
		auto-mal-update && rm -rvf "$(evry location -malexport_partial_update)"
	}
	# run malexport update https://github.com/purarue/malexport/
	bash "${HPIDATA}/malexport.job"
	evry 1 day -malexport_partial_update && {
		malexport_partial_update
	}
}

if ((ONCE)); then
	run
else
	while true; do
		run
		sleep 10m
	done
fi
