#!/usr/bin/env bash

contents="$(cat "$HOME/.config/newsraft/feeds")"

while read -r username; do
	if grep -q "rss/${username}.xml " <<<"$contents"; then
		echo "Skipping @$username, already present" >&2
		continue
	fi
	echo "Adding @$username" >&2
	file="${HOME}/.cache/tiktok-local-rss/rss/${username}.xml"
	if [[ ! -f "$file" ]]; then
		echo "While adding $username, $file not found" >&2
		continue
	fi
	printf 'file://%s "%s"\n' "$file" "$username" >>"$HOME/.config/newsraft/feeds"
done < <(spkglist "$XDG_DOCUMENTS_DIR/tiktok.txt")
