#!/usr/bin/env bash
# updates my rss feed, if I don't already have it open
# If newsraft is not open, this reloads all items and
# saves how many items are unread to ~/.cache/rss-unread
# If it fails, does not write

readonly CACHE_FILE="${XDG_CACHE_HOME:-${HOME}/.cache}/rss-unread"

if pgrep -x newsraft >/dev/null; then
	echo "Newsraft is active, skipping update..." >&2
	exit 1
else
	[[ -z "$SKIP_RELOAD" ]] && newsraft -e reload-all >/dev/null
	unread="$(newsraft -e print-unread-items-count)" || exit $?
	is-integer "$unread" >/dev/null && echo "$unread" >"${CACHE_FILE}"
fi
