#!/bin/zsh
#runs which, and prints the contents of the function/script

function which-cat() {
	local COMMAND_OUTPUT USER_INPUT
	USER_INPUT="${1:?Must provide a command to lookup}"
	if COMMAND_OUTPUT="$(which "${USER_INPUT}")"; then
		# if the file is readable
		if [[ -r "${COMMAND_OUTPUT}" ]]; then
			if iconv --from-code="utf-8" --to-code="utf-8" "${COMMAND_OUTPUT}" >/dev/null 2>&1; then
				# if in pipx_isolate bin, reroute to source script
				if grep -q 'pipx_isolate/bin' "$COMMAND_OUTPUT"; then

					COMMAND_OUTPUT="$(where "$USER_INPUT" | grep -v "pipx_isolate/bin" | head -n1)"
					command cat "$COMMAND_OUTPUT"
				else
					command cat "$COMMAND_OUTPUT"
				fi
			elif gzip -t "${COMMAND_OUTPUT}" >/dev/null 2>&1; then
				zcat "${COMMAND_OUTPUT}"
			else
				file "${COMMAND_OUTPUT}"
			fi
		else
			# error finding command, or its an alias/function
			printf '%s\n' "${COMMAND_OUTPUT}"
		fi
	else
		printf '%s\n' "${COMMAND_OUTPUT}" >&2
	fi
}

# vim: ft=bash
