#!/bin/zsh

# automatically open certain file types by just
# typing the name as a command
alias -s {md,html,txt}=nvim

# save ls so it can be used elsewhere if I want
abbrev-alias lls='/usr/bin/ls --color=never'
compdef _eza eza-defaults
alias eza-defaults='eza --git --octal-permissions --header --group-directories-first'
# alias ls to eza
case "$ON_OS" in
# disable icons on:
mac*)
	alias ls='eza-defaults'
	;;
*)
	alias ls='eza-defaults --icons'
	;;
esac
alias tree='ls --tree --git-ignore'
alias ll='ls --header --long'
alias la='ll --all'
alias sl='ls'
alias dc='cd' # never going to use the reverse-polish calculator, is *always* a typo

# https://github.com/neovim/neovim/issues/1808
alias killall-nvim='killall -9 nvim'

abbrev-alias ccat='/usr/bin/cat'

# yadm aliases to work like git aliases, to manage dotfiles
abbrev-alias yds='yadm diff --staged'
abbrev-alias yst='yadm status'
abbrev-alias yd='yadm diff'
abbrev-alias ysu='yadm status -u'
alias ya='yadm add' # no abbrev because slow autocompletion
abbrev-alias yA='yadm add --all'
abbrev-alias yc='yadm commit'
abbrev-alias yp='yadm push'
abbrev-alias yl='yadm pull --recurse-submodules'
abbrev-alias yrh='yadm reset'
abbrev-alias yrhh='yadm reset --hard'
abbrev-alias ylols='yadm log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'' --stat'
ydh() {
	yadm diff HEAD~"${1:-1}"
}
ycp() {
	if (($# == 0)); then
		yadm commit && yadm push
	else
		yadm commit -m "$*" && yadm push
	fi
}
# compdef _git-diff ydh
# compdef _git-commit ycp
alias e=editor
abbrev-alias rgv='rg --vimgrep'

# conflicts() {
# 	local chosen sourcefile
# 	chosen="$(sync-conflicts "$1" -print -quit)"
# 	if [[ -z "$chosen" ]]; then
# 		echo "No conflicts found" >&2
# 		return 1
# 	fi
#
# 	# get the source file and run script on it to open in vimdiff
# 	sourcefile="$(echo "$chosen" | awk -F '.sync-conflict' '{print $1}')"
# 	vimdiff-syncthing-conflict "$sourcefile"
# }

# Shorthands, or adding some default flags to utilities
alias 'xargsl=xargs -I {} sh -c' # line-based xargs
alias 'cp=cp -v'
alias 'curl=curl --silent'
alias 'less=less --ignore-case'
alias 'lessansi=less --RAW-CONTROL-CHARS'
alias 'taill=tail --lines 50'
alias dr='dragon-drop'
function events() {
	calcurse-upcoming "$@" | lower
}
alias drx='dragon-drop --and-exit'
alias du='du -h'
alias df='df -h'
alias ab='e "${XDG_DOCUMENTS_DIR}/addressbook"'
alias abook=abookc
alias history='history 0'
alias free='free --human'
alias rb='restic-backup backup'
rgi() {
	rg --ignore-case "$*"
}
# rg, for working with quickfix lists
rgqf() {
	rg --no-heading --with-filename --line-number "$@"
}

# todo.txt
alias ft='todo full'
alias ti='todo interactive'
alias td='todo edit'

alias ghd='gh dash'
alias rr='rifle'
alias optipng='optipng -o5'
alias R=ranger
alias nr='neomuttr'
urban() {
	udict "$@" | less
}
alias xxd='hexyl'
alias calc='ipython3 --profile=calculator'
alias XMODMAP-RESET='xmodmap-reset' # in case Im stuck in capslock
alias 'countdown=termdown'
# shorthand for copying to clipboard
alias cl='clipcopy'
alias 'ml=mailsync-loop'
alias 'confirm=fzf --multi'
alias 'up=TERM=xterm up'
alias screens='cd $SCREENSHOTS'

abbrev-alias rrm='/usr/bin/rm'

# dont use rmtrash on android, doesn't work
case "$ON_OS" in
android*)
	alias rm='rm -v'
	;;
*)
	alias rm='trash-put -v'
	;;
esac

alias d="kitten diff"

# background jobs
alias sctl='super --ctl'
alias sc=sctl
alias sclp=server_clipboard
alias slogs='super --logs'

# custom non-standard stuff
# shorthand for reverse of https://purarue.xyz/d/star?dark
unstar() {
	star "$1" DELETE
}
# create a notes file in the current directory
alias create-note='touch "$(daystamp_).md"'
# pipe some command into stripcolors, removes any ANSI color codes
alias stripcolors="sed 's/\x1B\[[0-9;]\+[A-Za-z]//g'"
alias '?=duck'                                         # alias ? to duck, searches duckduckgo in lynx
alias tetris='autoload -Uz tetriscurses; tetriscurses' # tetris in zsh!
alias rgf='rg --files | rg'                            # search against filepaths with rg
# start a server to test HTTP requests against
alias httpbin='docker run -p 80:80 kennethreitz/httpbin'

# stop import from crashing my system for some reason
alias 'import=printf "Use /usr/bin/import instead\n"'
_set_theme() {
	terminal-set-theme "$1"
	export TERMINAL_THEME="$1"
}

alias light-theme='_set_theme Light'
alias dark-theme='_set_theme Dark'
