directory: ~/Music
library: ~/Documents/beet.db

import:
  copy: no
  incremental: yes
  incremental_skip_later: yes
plugins:
  - convert
  - info
  - export
  - ftintitle
  - discogs
  - scrub
  - zero
  - lastgenre
  - yearfixer
  - edit
original_date: yes

# plugin config
zero:
  fields: genre comments
  comments: [EAC, LAME, support, from.+collection, bandcamp, "ripped by"]
  update_database: true

# automatically convert non mp3 files to mp3 during import
convert:
  auto: yes
  extension: mp3
