directory: ~/Music
library: ~/Documents/beet.db

import:
  write: yes #  write ID3/data to files
  copy: no # by default dont move files
  incremental: yes
  incremental_skip_later: yes
plugins:
  - filetote
  - convert
  - fetchart
  - info
  - export
  - ftintitle
  - discogs
  - scrub
  - zero
  - lastgenre
  - edit
original_date: yes

paths:
  default: $albumartist/$album%aunique{}/$disc-$track $title
  comp: Various_Artist/$album%aunique{}/$disc-$track $title
  albumtype:soundtrack: Soundtracks/$album%aunique{}/$disc-$track $title
  filename:cover.jpg: $albumpath/cover

# plugin config
filetote:
  extensions: .png .jpg
  filename: "cover.jpg"
  print_ignored: yes

zero:
  fields: comments
  comments: [EAC, LAME, support, from.+collection, bandcamp, "ripped by"]
  update_database: true

# automatically convert non mp3 files to mp3 during import
convert:
  auto: yes
  extension: mp3

ftintitle:
  auto: yes

lastgenre:
  auto: yes
  count: 1
  fallback: ""
  source: album

fetchart:
  sources:
    - filesystem
    - coverart: release
    - coverart: releasegroup
    - itunes
    - amazon
    - albumart
  maxwidth: 800
