directory: ~/Music
library: ~/Documents/beet.db

import:
  copy: no
  incremental: yes
  incremental_skip_later: yes
plugins:
  - copyfileartifacts
  - convert
  - fetchart
  - info
  - export
  - ftintitle
  - discogs
  - scrub
  - zero
  - lastgenre
  - edit
original_date: yes

paths:
  filename:cover.jpg: $albumpath/cover

# plugin config
copyfileartifacts:
  extensions: .png .jpg
  filename: "cover.jpg"
  print_ignored: yes

zero:
  fields: genre comments
  comments: [EAC, LAME, support, from.+collection, bandcamp, "ripped by"]
  update_database: true

# automatically convert non mp3 files to mp3 during import
convert:
  auto: yes
  extension: mp3

ftintitle:
  auto: yes

lastgenre:
  auto: yes

fetchart:
  sources:
    - filesystem
    - coverart: release
    - coverart: releasegroup
    - itunes
    - amazon
    - albumart
  maxwidth: 800
