# This file is converted by https://github.com/seanbreckenridge/shortcuts
# into standalone shell scripts

# default_shebang = "#!/bin/sh"
# default_mode = "0755"

# fuzzy match config file names, open one to edit
[edit-config]
command = '''cat <(echo -e "${HOME}/.profile\n${HOME}/.gitignore") <(fd --full-path "${HOME}" ~/.config ~/.scripts ~/.todo --type f -H -E "discord" -E "google-chrome" -E "Slack" -E "repo.git" -E "Code - OSS" -E "chromium" -E "Electron" -E "Atom" -E "Pinta" -E "pulse" -E "mono.addins" -E "configstore" -E "autostart" -E "largechar" -E "gcloud" -E "Thunar") | fzf | xargs -r "$EDITOR"'''
shebang = "#!/usr/bin/env bash"

# 'launch' runs normally if called on command line, else
# launches a terminal and runs the command there
[ec]
command = 'launch edit-config'

# open the dotfiles git repository
[dotfiles]
command = '''yadm gitconfig --get remote.origin.url | /usr/bin/python3 -c "from giturlparse import parse; import subprocess, webbrowser; subprocess.run('open-browser'); webbrowser.open(parse(input()).urls[\"https\"])"'''

# print i3 bindings
# ignore volume and brightness bindings
[i3binds]
command='''sed 's/^bindsym --release/bindsym/g' "${HOME}/.config/i3/config" | awk '/^bindsym/ {$1=""; print substr($0, 2, 9999)}' | grep -Ev "pactl|brightness"'''

# prompt i3 bindings w/ rofi and run one of the commands
[i3binds-prompt]
command='''i3-msg "$(i3binds | rofi -dmenu -width 50 -lines 30 -location 5 -p "Pick a command to run > " | sed 's/--no-startup-id //g' | cut -d" " -f 2-)"'''

# reload firefox
[reload-browser]
command='xdotool search --class "Firefox" key --window %@ "ctrl+r"'

# print the date in the us format
[usdate]
command = 'date "+%m/%d/%y"'

# print current git configuration
[gitcfg]
command = "git config --list | cat"
link = "gitconfig"

# generate a good ssh key
[good-ssh-keygen]
command = 'ssh-keygen -t rsa -b 4096 -o -a 100'
link = "ssh-keygen-good"  # so that it autocompletes from ssh-keygen

# get gitignores for different languages
[gi]
command = '''
if [ ! "$( echo "$@" | tr -d "\n\r" )" = "" ] && [ ! "$1" = "list" ]; then
  printf "tags*\n"
fi
curl -sL "https://gitignore.io/api/$*"
printf "\n"
'''

# open ranger
[rn]
command = 'launch ranger'

# wait for internet connection and ping me
[wfi]
command='wait-for-internet && notify-send "INTERNET" && mpv /usr/share/sounds/freedesktop/stereo/message.oga > /dev/null 2>&1'

# prompts the user for input with a basic rofi input prompt
# additional options can be given after rofi-input
[rofi-input]
command = '''rofi -dmenu -theme-str 'listview {enabled: false;}' "$@"'''

# searches trakt/letterboxd for a movie
[moviesearch]
command = '''
SEARCH_STR=$(rofi-input -p "Search for a movie > " | awk '{$1=$1; print}' | tr " " "+")  # awk removes leading/trailing spaces
[ -z "$SEARCH_STR" ] && exit 1
open-browser
xdg-open "https://trakt.tv/search/movies?query=${SEARCH_STR}&utf8=%E2%9C%93"
xdg-open "https://letterboxd.com/search/films/${SEARCH_STR}"
'''

# searches trakt for a tv show
[tvsearch]
command = '''
SEARCH_STR=$(rofi-input -p "Search for a TV show > " | awk '{$1=$1; print}' | tr " " "+")
[ -z "$SEARCH_STR" ] && exit 1
open-browser
xdg-open "https://trakt.tv/search/shows?query=${SEARCH_STR}&utf8=%E2%9C%93"
'''

# generates a password and puts it on your clipboard
# uses https://github.com/seanbreckenridge/genpasswd
[genpass]
shebang = "#!/usr/bin/env bash"  # to make sure echo flags work
command = '''
pw=$(genpasswd "$@" | head -n 1 | tr -d "\n")
if [ "$(tty)" = "not a tty" ]; then
  notify-send "${pw}"
else
 echo -e "$pw"
fi
# copy to clipboard
echo -en "$pw" | xclip -selection clipboard
'''

# play music in the current directory, recursively
[play-music]
command='fd --type f -E "*jpg" -E "*png" | mpv --playlist=- --no-audio-display'


# Plays songs from this folder, recursively, randomly
[shuffle-music]
command='find . -type f ! -name "*jpg" ! -name "*png" | shuf | mpv --playlist=- --no-audio-display'

