# This file is converted by https://github.com/seanbreckenridge/shortcuts
# into standalone shell scripts
default_shebang = "#!/bin/sh"

[list-config]
shebang = "#!/bin/zsh"
command = '''
# list all of my configuration files, by matching combining
# yadm list and a couple search commands
{
	cd && yadm list | sed "s#^#$HOME/#"
	fd --type=file -H -E '__pycache__' -E '.mypy_cache' --full-path "${HOME}" "${XDG_CONFIG_HOME}/todo" "${XDG_CONFIG_HOME}/bookmark.txt" "${ZDOTDIR}" "${XDG_CONFIG_HOME}/yadm" "${XDG_CONFIG_HOME}/my"
} | grep -v "system-config" | exists | sort -u
'''

[ec]
command = '''
cd ~ || exit $?
# fuzzy match list-config names, open one to edit (Edit Config)
fzfcache list-config | sed "s#^$HOME/##g" | fzf +m -q "$*" | xargs -r -I {} editor "$HOME/{}"
'''

[dotfiles]
command='''
# open the dotfiles git repository
cd "${HOME}/.local/share/yadm/repo.git" || exit 1
exec git open
'''

[i3binds]
command='''
# print i3 bindings
# ignore volume and brightness bindings
sed 's/^bindsym --release/bindsym/g' "${HOME}/.config/i3/config" | awk '/^bindsym/ {$1=""; print substr($0, 2)}'
'''

["i3binds-prompt"]
command='''
# prompt i3 bindings w/ rofi and run one of the commands
i3-msg "$(i3binds | rofi -dmenu -width 50 -lines 30 -location 5 -p "Pick a command to run > " | sed 's/--no-startup-id //g' | cut -d" " -f 2-)"'''

[reload-browser]
command='''
# reload firefox (Navigator is firefox's WM_CLASS)
# the i is to enter insert mode in firefox (I use vimium)
# \C is control, r is r, to refresh
exec xvkbd -window Navigator -text "i\Cr"
'''

[usdate]
command = '''
# print the date in the us format
exec date "+%m/%d/%y"
'''

[gi]
command = '''
# get gitignores for different languages
if [ ! "$(echo "$@" | tr -d "\n\r")" = "" ] && [ ! "$1" = "list" ]; then
	printf "*.pdf\n"
fi
curl -sL "https://gitignore.io/api/$*"
printf "\n"
'''

[wfi]
command='''
# wait for internet connection and ping me
command -v tttlog >/dev/null 2>&1 && tttlog "$(basename "$0")"
wait-for-internet "$@" && {
	notify "INTERNET"
	playping
}
'''

[wfib]
command='''
# wfi, and then reload the browser
wfi
exec reload-browser
'''

[moviesearch-trakt]
command = '''
# searches trakt for a movie
[ -z "$SEARCH_STR" ] && SEARCH_STR=$(input-dialog "Search for a movie > " | chomp | tr " " "+")
[ -z "$SEARCH_STR" ] && exit 1
command -v tttlog >/dev/null 2>&1 && tttlog "$(basename "$0") $SEARCH_STR"
exec openurl "https://trakt.tv/search/movies?query=${SEARCH_STR}&utf8=%E2%9C%93"
'''

[moviesearch-letterboxd]
command = '''
# searches letterboxd for a movie
[ -z "$SEARCH_STR" ] && SEARCH_STR=$(input-dialog "Search for a movie > " | chomp | tr " " "+")
[ -z "$SEARCH_STR" ] && exit 1
command -v tttlog >/dev/null 2>&1 && tttlog "$(basename "$0") $SEARCH_STR"
exec openurl "https://letterboxd.com/search/films/${SEARCH_STR}"
'''

[moviesearch]
command = '''
# searches trakt/letterboxd for a movie
SEARCH_STR=$(input-dialog "Search for a movie > " | chomp | tr " " "+")
[ -z "$SEARCH_STR" ] && exit 1
export SEARCH_STR
moviesearch-trakt &
moviesearch-letterboxd &
wait
'''

[tvsearch]
command = '''
# searches trakt for a tv show
SEARCH_STR=$(input-dialog "Search for a TV show > " | chomp | tr " " "+")
[ -z "$SEARCH_STR" ] && exit 1
command -v tttlog >/dev/null 2>&1 && tttlog "$(basename "$0") $SEARCH_STR"
exec openurl "https://trakt.tv/search/shows?query=${SEARCH_STR}&utf8=%E2%9C%93"
'''

[mediasearch]
command = '''
if SELECTED=$(printf "moviesearch\ntvsearch" | picker -p "Search Media Type > "); then
	exec "$SELECTED"
fi
'''

[genpass]
shebang = "#!/usr/bin/env bash"
command ='''
# generates a password and puts it on your clipboard
# uses https://github.com/seanbreckenridge/genpasswd
if ! pw=$(genpasswd "$@"); then
	echo "$pw" >&2
	exit 1
fi
pw="$(head -n 1 <<<"$pw")"
# send notification and copy to clipboard
clp <<<"${pw}"
printf '\n'
'''

[list-images]
command='''exec fd '.*\.(png|jpeg|jpg)$' "$@"'''

[play-music]
command='''
# play music in the current directory, recursively
list-music | sort -n | mpv --playlist=- --no-audio-display
'''

[shuffle-music]
command='''
# Plays songs from this folder, recursively, randomly
list-music | shuf | mpv --playlist=- --no-audio-display
'''

[screenshot-to-imgur]
command='''
# uploads the most recent screenshot from
# ~/Pictures/Screenshots to imgur
FILENAME="$(lastpic)" || exit 1
notify "Uploading imgur..."
imgur-uploader "$FILENAME"
IMGUR_URL="$(clippaste)"
printf "%s\n" "$IMGUR_URL" >>/tmp/imgur_urls.log
notify "Uploaded Image to Imgur:" "$IMGUR_URL"
'''

[twitch-stream]
command = '''
# open chatterino and use mpv to stream from twitch
STREAMER="${1:?Pass the twitch user to stream from as the first argument.}"
pgrep -x chatterino >/dev/null || setsid chatterino >/dev/null 2>&1 &
MPVF_PICKER=rofi setsid mpvf "https://www.twitch.tv/${STREAMER}" >/dev/null &
'''

[clipedit]
command = '''
# edit your clipboard in vim
launch "clippaste | vipe | clipcopy"
'''
link = 'edit-clipboard'

# shorthand for clipcopy
[cl]
command='clipcopy'

[clipreset]
command='''
# reset the clipboard formatting
notify "resetting clipboard..."
clippaste | clipcopy
'''

[lynx]
shebang="#!/bin/zsh"
command = '''
# override the lynx binary by
# placing the lynx shortcut
# on $PATH first
LYNX_PATH="$(where lynx | grep -m1 -v "$SHORTCUTS_DIR")" || exit $?
exec "$LYNX_PATH" -accept_all_cookies -cfg="${XDG_CONFIG_HOME}/lynx/lynx.cfg" "$@"
'''

[printer-server]
command = '''
# open the printer interface in the browser
PRINTER_PORT=$(sudo cat /etc/cups/cupsd.conf | grep -i "Listen localhost" | cut -d":" -f2)
printf "localhost:%d" "$PRINTER_PORT" | openurl
'''

[drive-mount]
command= '''
# start the ldm (light device mounter) daemon, to mount devices
echo "use lsblk -f to view disk IDs"
exec sudo ldm -u "$(whoami)"
'''

[ipinfo]
command='''
# get my ip information
curl -s ipinfo.io | gron | grep -v 'json.readme' | gron -u | jq -r 'to_entries[] | "\(.key): \(.value)"'
'''

[webcam-test]
command='exec /usr/bin/mpv /dev/video0'

[webcam-pic]
command='''
# open mpv to save a picture (using webcam) in ~/Pictures/pics

declare pics
pics="${XDG_PICTURES_DIR:?XDG_PICTURES_DIR environment variable not set}/pics"
[[ ! -d "$pics" ]] && mkdir -p "$pics"
cd "$pics" || exit 1
# open mpv so I can take a picture
mpv /dev/video0
exec launch ranger "$pics"
'''
shebang='#!/usr/bin/env bash'
link='camera'

[image-dimensions]
command='''
# print the image dimensions for one or more images
for f in "$@"; do
	img_size="$(exiftool "$f" | grep "Image Size")"
	[ -z "$img_size" ] && printf "Could not get 'Image Size' for %s" "$f" 1>&2 || printf "%s %s\n" "${img_size#*: }" "$f"
done
'''

[remove-extension]
command='''
# remove the extension from a filename
FILEPATH="${1:?You must provide a filepath to remove the extension for.}"
echo "${FILEPATH%%.*}"
'''

[replace-extension]
command='''
# replace the extension for a filename
FILEPATH="${1:?Have to provide a filepath to replace the extension for}"
REPLACE_EXTENSION="${2:?Must provide extension to replace extension with}"
echo "${FILEPATH%%.*}.${REPLACE_EXTENSION#.}"
'''

[get-extension]
command='''
# remove the extension from a filename
FILEPATH="${1:?You must provide a filepath to remove the extension for.}"
echo "${FILEPATH##*.}"
'''

[to-png]
command='''
# convert an image to png
FILEPATH=${1:?Must provide image to convert}
exec convert "$FILEPATH" "$(replace-extension "$FILEPATH" png)"
'''

[to-jpeg]
command='''
# convert an image to png
FILEPATH=${1:?Must provide image to convert}
exec convert "$FILEPATH" "$(replace-extension "$FILEPATH" jpg)"
'''
link = "to-jpg"

[to-icon]
command='''
# convert an image to a 16x16 icon - to favicon size
FILEPATH=${1:?Must provide image to convert}
NEW_FILEPATH="$(remove-extension "${FILEPATH}")-icon.png"
exec convert -resize x16 -gravity center -crop 16x16+0+0 -flatten -colors 256 "${FILEPATH}" "${NEW_FILEPATH}"
'''

[rotate-img]
command='''
FILEPATH=${1:?Must provide image to convert}
exec convert "${FILEPATH}" -rotate 90 "${FILEPATH}"
'''

[file-mime]
command='''
# get mime type for one or more files
# this is the same as what rifle (ranger) does
exec file --mime-type -Lb "$@"
'''

# shorthand for sending lines from vim to pastebin
[vix]
command='exec ix -v'

[clp-args]
command='''
# clp, but accepts input as arguments
echo "$*" | clp
'''

# lots of date shorthands

[tstamp]
command="exec date +'%Y%m%d%H%M%S'"

[daystamp]
command='exec date "+%Y-%m-%d"'

["daystamp_"]
command='exec date "+%Y_%m_%d"'

[now]
command='exec date +"%A, %B %e, %Y, %l:%M:%S%p"'

[epoch]
command='exec date +"%s"'

[weekday]
command='exec date +"%A" | lower'

[month]
command='exec date +"%B" | lower'

[year]
command='exec date +"%Y"'

[lastpic]
shebang = "#!/usr/bin/env bash"
command='''
case "$ON_OS" in
	linux*)
		exec newest "$@" "${SCREENSHOTS:?No SCREENSHOTS environment variable set}"
		;;
	mac*)
		find "${HOME}/Desktop" -iname 'screen shot*' | tail -n1 || exit $?
		;;
esac
'''

[lastpicpreview]
command='exec rifle "$(lastpic)"'

[lastpicdrag]
command='dragon-drop -x "$(lastpic)"'
link = "draglastpic"

[urlpicpreview]
command='''
# preview a picture from a URL
img-download "$@" || exit $?
rifle "$(clippaste)"
'''

[lastdown]
command='exec newest "$@" "${XDG_DOWNLOAD_DIR:?No XDG_DOWNLOAD_DIR environment variable set}"'

[mvlast]
command='''
FILE="$(lastdown)" || exit 1
exec mv -v "${FILE}" "./$1"
'''

[mvlastpic]
command='''
FILE="$(lastpic)" || exit 1
exec mv -v "${FILE}" "./$1"
'''

[vic]
command='''
EXECUTABLE="${1:?No Executable provided}"
LOCATION="$(command -v "${EXECUTABLE}")" || exit $?
exec editor "${LOCATION}"
'''

[list-config-no-hist]
command='''
list-config | grep -vE -e "zsh_history|compdump" -e "$SHORTCUTS_DIR"
'''


[grep-dotfiles]
shebang="#!/usr/bin/env bash"
command='''
# searches all my configuration for a string
# passes arguments received to grep
list-config-no-hist | xargs grep -Hrin "$@"
'''

[cheat]
command='''
command -v tttlog >/dev/null 2>&1 && tttlog "$(basename "$0") $*"
exec curl -s "https://cheat.sh/$*"
'''

[speedtest]
command='wait-for-internet --text "Waiting for internet..." && exec python3 -m speedtest "$@"'

[rcut]
command='''
# cut, but indexing from the right
rev | cut "$@" | rev
'''

[mpv-corner]
command='''
# mpv wrapper to open a video with mpv and put it in the bottom right corner
setsid -f mpv --x11-name=mpv_stream_media "$@" >/dev/null 2>&1
'''

[youtube-dl]
command='''exec python3 -m yt_dlp -o '%(title)s.%(ext)s' -ci "$@"'''

[create-youtube-dl-resolution-str]
command='''
# defaults to about 480p
# otherwise, grabs the format from the FORMAT environment variable
# prints the format string for a particular resolution
FORMAT="${FORMAT:-550}"
exec printf 'bestvideo[height<=%d]+bestaudio/best[height<=%d]' "$FORMAT" "$FORMAT"
'''

[stream-corner]
command='''
# streams and sets the instance name on the mpv window
# this is used with a for_window hook in i3 to put the
# window in the bottom right
exec stream-media --x11-name=mpv_stream_media "$@"
'''

[stream-corner-at]
command='''
# set the FORMAT environment variable to specify maximum height/width
# defaults to about 480p
STREAM_MEDIA_CMD=mpv exec stream-corner --ytdl-format="$(create-youtube-dl-resolution-str)" "$@"
'''

[stream-corner-480]
command='exec stream-corner-at "$@"'

[stream-corner-720]
command='''
export FORMAT=850
exec stream-corner-at "$@"
'''

[stream-corner-1080]
command='''
export FORMAT=1100
exec stream-corner-at "$@"
'''

[stream-audio]
command='STREAM_MEDIA_CMD=mpv exec stream-media --no-video "$@"'

[youtube-dl-at]
command='''
# set the FORMAT environment variable to control resolution
exec youtube-dl -f "$(create-youtube-dl-resolution-str)" "$@"
'''

[youtube-dl-480]
command='''
# download at about 480p
exec youtube-dl-at "$@"
'''

[youtube-dl-720]
command='''
# download at about 720p
export FORMAT=850
exec youtube-dl-at "$@"
'''

[stream-from-firefox]
command='''
# copies the current URL from firefox, and starts streaming it with stream-at-480
# escape, then yy (yank the URL; using the vimium extension)
xvkbd -window Navigator -text "\Eyy"
sleep 1 # just to make sure its copied
exec stream-corner-480
'''

[discord-browser]
command="exec openurl 'https://discord.com/login'"

[newsboat-force]
command='''
# if another instance of newsboat is open, kill it and open one here
# specifically useful incase newsboat -x reload is going on in the background
pgrep -x newsboat && pkill -x newsboat
cd "${XDG_DOWNLOAD_DIR:-${HOME}/Downloads}" || exit 1
newsboat
exec i3-msg exec update-rss # update rss afterwards, to update menu bar icon
'''

[neomuttr]
command='''
# neomutt and refresh the i3 block
neomutt && i3blocks-refresh-mk mail
'''

[alacritty-tmux]
command='exec alacritty -e tmux'

[extracturls]
command='''
# receives text from STDIN, extracts unique URLs
# pypi.org/project/urlextract
urls="$(urlextract | sort -u)"
if [ -z "${urls}" ]; then
	notify "No URLs found in text"
	exit 1
fi
printf "%s\n" "${urls}"
'''

[ssh-keygen-good]
command='exec ssh-keygen -t rsa -b 4096 -o -a 100'

[mystarsfzf]
command='''
# https://github.com/seanbreckenridge/oh-my-stars
PICKED="$(fzfcache mystars "$@" | fzf --ansi)" || exit $?
printf '%s\n' "${PICKED}"
URL="$(echo "${PICKED}" | urlextract)"
# if a URL was extracted, copy it to my clipboard
[[ -n "${URL}" ]] && {
	printf '%s' "${URL}" | clipcopy
	printf '%s\n' "${URL}"
}
'''
shebang="#!/usr/bin/env bash"

[screens]
command='exec nsxiv -t "${SCREENSHOTS}"'

[up-live]
command='TERM=xterm exec up --unsafe-full-throttle'
shebang="#!/bin/zsh"

[watchtwitch]
command='''
twitchlive -output-format json | jq -r '.[] | .username' | picker -p "who to watch? " | xargs -r twitch
'''

[reshortcuts]
command='''
set -o pipefail
cd || exit $?
[[ -n "${SHORTCUTS_DIR}" ]] && [[ -d "${SHORTCUTS_DIR}" ]] && rm -rf "${SHORTCUTS_DIR}"
echo "Creating/formatting shortcuts..."
DEBUG_OUTPUT="$(shortcuts create --debug && fd . "${SHORTCUTS_DIR}" -X rifleman 2>&1)" || {
	echo "$DEBUG_OUTPUT"
}
'''
shebang="#!/usr/bin/env bash"

[i3-jinja]
command = '''
set -x
I3_DIR="${HOME}/.config/i3"
cd "${I3_DIR}" || exit $?
exec j2 config.j2 -o config -f yaml <config.yaml
'''
shebang="#!/usr/bin/env bash"

[alarm]
command = 'exec paplay /usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga'

[synonym]
command = '''
word="${1:?Provide the word to list synonyms as first argument}"
moby "${word}" | grep ',' | sed 's/,/\n/g' | chomp
'''

[fzfp]
command = 'fzf --preview="${HOME}/.config/fzf_preview {}" "$@"'

[largechar-clipboard]
command='''
CONTENTS="$(clippaste)"
[ -z "${CONTENTS}" ] && exit 1
printf '%s' "${CONTENTS}" | largechar -c
'''

[syncgui]
command = "exec openurl 'localhost:8384'"

[sqlitebrowser-]
command='''
# on linux, call the binary directly
havecmd 'sqlitebrowser' && exec sqlitebrowser "$@"
# on mac, this is installed into /Applications/
exec open -a DB\ Browser\ for\ SQLite "$@"
'''

[clr]
command = '''print-or-notify "$(ttally recent food "$@")"'''

[clrs]
command = '''clr -r calories "$@"'''

[mz]
command = '''
# use cached https://github.com/seanbreckenridge/projects repository information
# to quickly open one of my Github repositories
jq -r '.[] | .html_url' <"${REPOS}/projects/cache.json" | fzf | clipcopy
'''

[sync-neomutt]
command = '''
# wait for internet, sync my mail, then launch neomutt
wait-for-internet && mailsync
i3blocks-refresh-mk mail
neomutt
i3blocks-refresh-mk mail
'''

[trakt-progress]
command = 'exec openurl "https://trakt.tv/users/purplepinapples/progress"'

[mal-recent]
command = 'exec openurl "myanimelist.net/animelist/purplepinapples?status=7&order=5"'

[lynx-from-stdin]
command = 'exec lynx -stdin'

[lynx-dump]
command = 'exec lynx -stdin -dump'

[urldrag]
command = '''
# dragon a picture from my clipboard https://github.com/mwh/dragon
img-download || exit $?
exec dragon-drop -x "$(clippaste)"
'''

[albums]
command = 'exec openurl "https://sean.fish/s/albums"'

[boxes-python]
command='''
# create a comment box as a python comment, text piped from STDIN
exec boxes -dshell -pv1h2 "$@"
'''

[boxes-vim]
command="""boxes-python | tr '#' '\"'"""
link = "boxes-nvim"

[flake8c]
command='''
# flake8 with my default config -- https://sean.fish/d/.config/flake8?dark
exec flake8 --config ~/.config/flake8 "$@"
'''

[yadm-format]
shebang = "#!/bin/zsh"
command='''
# format and lint all my dotfiles
cd
yadm list | exists | rifleman -
yadm list | exists | rifleman - -a lint
'''

[listens-desc]
command='''
# https://github.com/seanbreckenridge/HPI-personal/blob/master/scripts/listens
exec listens --desc "$@"
'''

[unique]
command='''
# filter the text from something piped into this to unique lines
exec awk '!seen[$0]++'
'''

[path]
command = 'echo "$PATH" | tr ":" "\n"'

[bglogs]
command='''
tail -n "${1:-100}" /tmp/bgproc.log | epochguess -d":"
'''

[yh]
command='''
cd ~/.local/share/yadm/repo.git/ || exit $?
exec gh "$@"
'''

[calcursed]
command='''
exec calcurse -D "$CALCURSE_DIR" -C ~/.config/calcurse "$@"
'''

[set-kitty-theme]
command='''exec kitty +kitten themes --reload-in=all "${1:?Must provide theme as kwarg}"'''

[light-theme]
command = 'exec set-kitty-theme Light'

[dark-theme]
command = 'exec set-kitty-theme Dark'

[cl-quickfix]
command = '''
# pastes text from the clipboard and creates a quickfist list
# this is typically called from kitty -- which saves the
# output of the previous command, then calls this in a new window
# https://github.com/seanbreckenridge/dotfiles/blob/cdae322fa6b735d5ca12dd3248354b5eeaaab0be/.config/kitty/kitty.conf#L1581-L1588
set -e
exec nvim -q <(clippaste) +copen
'''
shebang = "#!/usr/bin/env bash"

[qf] # quickfix
command = '''
# usually used like qf <(grep -Hrin ...) or qf <(!!)
# to repeat last command and create a quickfix list
exec nvim -q "$@" +copen
'''

[lessi]
command = 'exec less -i "$@"'

[sreminders-notify]
command='''
SREMINDERS="$(sreminders)"
notify "${SREMINDERS:-No sreminders}"
'''

[average]
command = 'exec datamash mean 1'

[discord-suppress]
command = "exec sed -e 's/^/</' -e 's/$/>/'"

[primes]
command = 'exec primesieve "$@" -p'

[text2html]
command = 'exec pygmentize -f html "$@"'

[tmpfile]
command = '''
ext="${1:-tmp}"
echo "$(mktemp -d)/$(genpasswd -rsym -rnum).${ext}"
'''

[pipehtml]
command = '''
# given HTML on STDIN, create a tempfile with its contents
tmpf="$(tmpfile html)"
cat >"$tmpf"
exec printf '%s\n' "$tmpf"
'''

[html-head-all]
command='exec html-head -a css-dark-mode -a css-pre-wrap "$@"'

[pygmentize-styles]
command="pygmentize -L styles | grep '* ' | cut -c3- | sed -e 's/:$//'"

[pygmentize-html-style]
command='''
style="$(pygmentize-styles | fzf)" || exit $?
exec pygmentize -P style="$style" -O noclasses=True -f html "$@"
'''

[repos]
command = 'exec repos-list -f'
